theme: jekyll-theme-minima
name: Outcoder
markdown: kramdown
highlighter: rouge
default_lang: csharp
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
repository: OutcoderSoftware/OutcoderSoftware.github.io