name: Outcoder
markdown: kramdown
highlighter: rouge
default_lang: csharp
encoding: utf-8
repository: OutcoderSoftware/OutcoderSoftware.github.io
paginate: 5
paginate_path: "/Blog/page:num/"
gems: 
 - [jekyll-paginate]
 - jekyll-redirect-from
 - jekyll-sitemap
permalink: /blog/:categories/:year/:month/:day/:title/
excerpt_separator: '<a name="excerpt-end"></a>'
