name: Outcoder
markdown: kramdown
highlighter: rouge
default_lang: csharp
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
repository: OutcoderSoftware/OutcoderSoftware.github.io
paginate: 5
paginate_path: "/Blog/page:num/"
gems: 
 - [jekyll-paginate]
 - jekyll-redirect-from
permalink: /blog/:categories/:year/:month/:day/:title/
excerpt_separator: '<a name="read-more"></a>'